name: Python unit tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:

  build-and-test:
    name: Python unit tests
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            py: "3.14"
            sys_install: "sudo apt -y update && sudo apt -y install libboost-iostreams-dev"
          - os: macos-15
            py: "3.10"
            sys_install: "brew install boost"

    steps:
      - name: checkout repo & submodules
        uses: actions/checkout@v5
        with:
          submodules: true
          fetch-depth: 0

      - name: install deps
        run: |
          ${{ matrix.sys_install }}

      - name: Set up Python ${{ matrix.py }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.py }}

      - name: install python bindings
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install .

      - name: python unit tests
        run: |
          python -m pytest
